PATH_TO_AUTH_KEY=/tempCert/asap_auth.key
PATH_TO_SIGN_KEY=/tempCert/asap_sign.key
PATH_TO_P_12_FILE=/tempCert/A1111NEXERAXXXXX_auth.p12
PATH_TO_DER_FILE=/tempCert/S1111NEXERAXXXXX_firma.der
AUTH_PEM_FILE_PATH=/tempCert/A1111NEXERAXXXXX_auth.pem
SIGN_PEM_FILE_PATH=/tempCert/S1111NEXERAXXXXX_firma.pem

TYPE=JWT
SUB=CNCGLC92B10F839E^^^&2.16.840.1.113883.2.9.4.3.2&ISO
COMMON_NAME_AUTH=auth:S1#111NEXERAXXXXX

COMMON_NAME_INT=integrity:S1#111NEXERAXXXXX
SUBJECT_ORGANIZATION_ID=150
SUBJECT_ORGANIZATION=Regione Campania
LOCALITY=201150004
SUBJECT_ROLE=DRS
PATIENT_CONSENT=true
PURPOSE_OF_USE=TREATMENT
ACTION_ID=CREATE
APPLICATION_ID=RIS
APPLICATION_VENDOR=NEXERA
APPLICATION_VERSION=1.0