package it.nexera.ris.common.enums;

import it.nexera.ris.common.helpers.EnumHelper;
import it.nexera.ris.common.helpers.ResourcesHelper;

public enum ApplicationSettingsKeys {
    // Common settings
    PASSWORD_EXPIRATION_PERIOD,
    USER_DISABLE_PERIOD,
    USER_DISABLE_POLLING_TIME,
    ASAP_SIO_ADDRESS,
    SETTING_ASAP_SIO_INTEGRATION_URL,
    SETTING_ASAP_SIO_INTEGRATION_USERNAME,
    SETTING_ASAP_SIO_INTEGRATION_PASSWORD,
    ASAP_SIO_USER_FOR_PSD,
    ASAP_SIO_PASSWORD_FOR_PSD,
    REQUEST_EXPIRATION_PERIOD,
    STATISTIC_SERVER_IP,
    SIGNATURE_DAYS_LIMIT,

    EXAM_REQUEST_SUBMIT_POLLING_TIME,
    EXAM_REQUEST_CHECK_POLLING_TIME,
    EXAM_REQUEST_LABEL_READ_POLLING_TIME,
    EXAM_REQUEST_RESULT_POLLING_TIME,
    WAITING_LIST_STATUS_CHECK_POLLING_TIME,
    PSD_CHECK_NEW_PATIENTS_POLLING_TIME,
    PSD_CHECK_POLLING_TIME,
    MAX_STARTED_DAYS,

    RIS_REQUEST_SEND_POLLING_TIME,
    RIS_RESPONSE_TIMEOUT,
    LABORATORY_EXAMS_PORT,
    RIS_PORT,
    RIS_RESEND_COUNT,

    HL7_LISTEN_PORT,

    HL7_SEND_IP,
    HL7_SEND_PORT,
    HL7_MDM_SEND_RETRY_TIME,
    HL7_ORM_SEND_RETRY_TIME,

    HL7_SEND_REPO_IP,
    HL7_SEND_REPO_PORT,
    HL7_REQUEST_SEND_POLLING_TIME,
    HL7_DAYS_LIMIT,
    HL7_MAX_SEND_COUNT_LIMIT,

    HL7_REPORT_FORWARDING_IP,
    HL7_REPORT_FORWARDING_PORT,
    HL7_REPORT_FORWARDING_POLLING_TIME,
    HL7_REPORT_FORWARDING_START_DATE,
    HL7_REPORT_FORWARDING_HOURS,


//    SMTP_SERVER,
//    SMTP_PORT,
//    SMTP_USERNAME,
//    SMTP_PASSWORD,

    FILE_ENTITY_PATH,

    SESSION_TIMEOUT,
    SESSION_CHECK_TIMEOUT,
    SESSION_TIMEOUT_WITHOUT_USER,
    SESSION_TIMEOUT_INTERVAL_WITHOUT_USER,

    CLEAN_SHORT_REQUEST_INTERVAL,
    QUERY_TIMEOUT,
    TOKEN_EXPIRATION,

    IMAGE_PATH,

    INCLUDE_CDA2_IN_PDF,
    ENABLE_VALIDATION_CDA2,
    FSE_GATEWAY_ENDPOINT;
    ;

    // INSERT_PDF_INTO_CDA2;

    @Override
    public String toString() {
        return ResourcesHelper.getEnum(EnumHelper.toStringFormatter(this));
    }
}
