package it.nexera.ris.common.enums;

public enum CdaTags {
    FILE_ENTITY_ID,
    FILE_ENTITY_CREATE_DATE,
    FILE_ENTITY_VERSION,
    FIRST_ROOT_CODE,
    SECOND_ROOT_CODE,
    PATIENT_FISCAL_CODE,
    FIRST_HOSPITAL_NAME,
    PATIENT_ID,
    PATIENT_SURNAME,
    PATIENT_NAME,
    PATIENT_SEX_TYPE,
    PATIENT_BIRTH_DATE,
    USER_FISCAL_CODE,
    USER_FIRST_NAME,
    USER_LAST_NAME,
    REQUEST_ACCESS_NUMBER,
    REQUEST_SECTOR_DESCRIPTION,
    REQUEST_ITEMS_DESCR,
    EXAM_CODE,
    EXAM_DESCRIPTION,
    REQUEST_PERFORM_DATE,
    HISTORICAL_REPORT_RESULT,
    ITEM_LIST,
    INSERT_PDF,
    PATIENT_COUNTY,
    PATIENT_CITY,
    PATIENT_CAP,
    PATIENT_ADDRESS,
    PATIENT_BIRTH_CITY,
    PATIENT_BIRTH_CITY_CODE,
    CONFIDENTIALITY_CODE,
    IN_FULFILLMENT_OF_ID_CONTENT,
    EXTERNAL_PATIENT_CODE;


    public String getTag() {
        return String.format("%%%s%%", name().toLowerCase());
    }
}
