package it.nexera.ris.common.enums;

public enum UserPreferenceType {
    WORKLIST_ITEMS_PER_PAGE,
    WORKLIST_STATE,
    WORKLIST_EXAM_TYPE,
    WORKLIST_ORDER,
    WORKLIST_ORDER_TYPE,
    PDF_ZOOM,
    PDF_USE_DESCRIPTION,
    LABEL_PRINT_ACTIVE,
    LABEL_PRINT_PRINTER_NAME,
    LABEL_PRINT_COUNT,
    LABEL_PRINT_ACTIVE_DOCG,
    LABEL_PRINT_PRINTER_NAME_DOCG,
    LABEL_PRINT_COUNT_DOCG,
    AUTO_SAVE_DOCG,
    OPEN_PDF_DOCUMENT,
    PRIORITY_ALERT,
    REFERRING_DICTION,
    VOCAL_RECOGNITION;
}
